production:
  adapter:  postgresql
  host:     localhost
  encoding: unicode
  database: rails6
  pool:     5
  username: rails6
  password: RL{64hsaL9184XI
  template: template0

development:
  adapter:  postgresql
  host:     localhost
  encoding: unicode
  database: rails6
  pool:     5
  username: eminencehc
  password:
  template: template0